version: '3.5'
services:
  payment:
    container_name: be-go-practical-payment
    build:
      context: ./payment
      dockerfile: Dockerfile
    env_file:
      - ./payment/.docker.env
    networks:
      - be-go-practical-net
  order:
    depends_on:
      - postgres
      - payment
    container_name: be-go-practical-order
    build:
      context: ./order
      dockerfile: Dockerfile
    env_file:
      - ./order/.docker.env
    ports:
      - "8081:8081"
    networks:
      - be-go-practical-net

  postgres:
    container_name: be-go-practical-postgres
    image: postgres:15.2
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - be-go-practical-net

volumes:
  postgres-data:


networks:
  be-go-practical-net:
    driver: bridge
